name: Deploy to NCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: sjgaru/pic064:latest

      - name: Deploy to NCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            sudo docker pull sjgaru/pic064:latest
            ${{ secrets.NCP_PASSWORD }}
            sudo docker stop pic064 || true
            sudo docker rm pic064 || true
            sudo docker run -d --name pic064 -p 8080:8080 sjgaru/pic064:latest
